# Generated by Django 4.2.16 on 2024-09-22 17:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0003_remove_contact_family"),
    ]

    operations = [
        migrations.CreateModel(
            name="newsLetter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
            ],
        ),
    ]
