# Generated by Django 4.2.16 on 2024-09-24 14:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0004_newsletter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="subject",
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
