# Generated by Django 4.2.15 on 2024-09-20 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_cathegory_post_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cathegory',
            new_name='Category',
        ),
    ]
