# Generated by Django 4.2.15 on 2024-09-20 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_rename_cathegory_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumbImage',
            field=models.ImageField(default='blog_thumb/default.jpg', upload_to='blog_thumb/'),
        ),
    ]
