# Generated by Django 4.2.15 on 2024-09-20 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_thumbimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbImage',
            field=models.ImageField(default='blog_thumb/default.jpg', height_field=60, upload_to='blog_thumb', width_field=60),
        ),
    ]
