# Generated by Django 4.2.16 on 2024-09-20 15:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0008_alter_post_thumbimage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="thumbImage",
        ),
    ]
