# Generated by Django 4.2.16 on 2024-09-27 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0011_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="postc",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="blog.post",
            ),
            preserve_default=False,
        ),
    ]
