# Generated by Django 4.2.16 on 2024-09-27 08:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0012_comment_postc"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ["-createdDate"]},
        ),
        migrations.RenameField(
            model_name="comment",
            old_name="postc",
            new_name="post",
        ),
    ]
