# Generated by Django 4.2.16 on 2024-09-29 15:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0014_rename_post_comment_postc"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="login_require",
            field=models.BooleanField(default=False),
        ),
    ]
